# Generated by Django 4.1.7 on 2023-03-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombres y Apellidos')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=400, verbose_name='Asunto')),
                ('phone', models.IntegerField(verbose_name='Teléfono')),
                ('country', models.CharField(max_length=100, verbose_name='País')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
            ],
        ),
    ]
